# docker-compose for Hadoop services versioned to be largely equivalent to HDP v2.6.0.3
# for testing and development purposes

---
version: '3'
services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    environment:
      ZOO_MAX_CLIENT_CNXNS: 0
      ZOO_STANDALONE_ENABLED: "true"
    ports:
      - "2181:2181"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.156

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 10.6.0.156:2181
      KAFKA_ADVERTISED_HOST_NAME: 10.6.0.155
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    networks:
      vpcbr:
        ipv4_address: 10.6.0.155

  nimbus:
    image: storm:1.1
    container_name: nimbus
    command: storm nimbus -c supervisor.childopts="-Xmx1024m"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    restart: always
    ports:
      - 6627:6627
    networks:
      - vpcbr

  supervisor:
    image: storm:1.1
    container_name: supervisor
    command: storm supervisor -c supervisor.childopts="-Xmx1024m"
    ports:
      - 8000:8000
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus:nimbus
      - zookeeper:zookeeper
    restart: always
    networks:
      - vpcbr

  supervisor-ui:
    image: storm:1.1
    container_name: stormui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
      - supervisor
    links:
      - nimbus:nimbus
      - zookeeper:zookeeper
      - supervisor:supervisor
    restart: always
    ports:
      - 9090:8080
    networks:
      - vpcbr

  postgres:
    build: ../postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "admin"
      SCALE_PCORNET: 10
    networks:
      vpcbr:
        ipv4_address: 10.6.0.153

  nifi:
    build: ../nifi
    container_name: nifi
    ports:
      - "8080-8081:8080-8081"
    volumes:
      - "/mnt/data/baikal-devenv/nifi/data:/opt/nifi/data"
      - "../nifi/hdfs/:/opt/nifi/conf/hdfs"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.151

  notebook:
    build: ../jupyter
    container_name: notebook
    volumes:
      - "/mnt/data/baikal-devenv/jupyter/src:/home/jovyan/work"
    ports:
      - "8888:8888"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.150

  hadoop-namenode:
    build: ../hadoop
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    ports: # HOST:CONTAINER
      - "2222:2222"
      - "4040:4040"
      - "5678:5678"
      - "7077:7077"
      - "8020:8020"
      - "8088:8088"
      - "9001:9001"
      - "50070:50070"
      - "50090:50090"
    expose:
      - "8030-8050"
    environment:
      - HDFS_REPLICATION_FACTOR=1
      - HADOOP_NAMENODE_HOST=hadoop-namenode
      - SCALE_PCORNET=10
    volumes:
      - ../hadoop/startup.sh:/root/startup.sh
      - ../hadoop/load_fakeCDM.sh:/root/load_fakeCDM.sh
      - ../hadoop/hive_install.sh:/root/hive_install.sh
      - ../hadoop/hive-site.xml:/root/hive-site.xml
      - ../hadoop/hive_interpreter.json:/root/hive_interpreter.json
      - "/home/${USER}/code:/home/hadoop/code"
      - ../hadoop/slaves-config:/config:ro
      - ../hadoop/deployments:/deployments:ro
    tty: true
    networks:
      vpcbr:
        ipv4_address: 10.6.0.157

  hadoop-datanode1:
    build: ../hadoop
    container_name: hadoop-datanode1
    hostname: hadoop-datanode1
    ports:
      - "8042:8042"
      - "50075:50075"
    expose:
      - "34000-48000"
      - "50010"
      - "50020"
      - "50040"
    environment:
      - HDFS_REPLICATION_FACTOR=1
      - HADOOP_NAMENODE_HOST=hadoop-namenode
    volumes:
      - ../hadoop/slaves-config:/config:ro
    links:
      - hadoop-namenode
    tty: true
    networks:
      vpcbr:
        ipv4_address: 10.6.0.158

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/24
